# Service Object To Access Application
apiVersion: v1
kind: Service
metadata:
  name: calc-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 32000
  selector:
    app: calc

